/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hoppe' at '24/03/14 2:41 PM' with Gradle 1.11
 *
 * @author hoppe, @date 24/03/14 2:41 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
